import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Lottie from 'react-lottie';
import agricultura1 from '../lotties/agricultura1.json'
const Home: NextPage = () => {
  const defaultOptions = {
    loop: true,
    autoplay: true,
    animationData: agricultura1,
    rendererSettings: {
      preserveAspectRatio: "xMidYMid slice"
    }
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com"/>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap" rel="stylesheet" />

      </Head>

      <main className={styles.main}>
        <div className={styles.containerApresetation}>
          <div className={styles.containerApresetation__text}>
            <h1>
              Jr. Agropecas
            </h1>
            <p>
              A Jr. Agropecas é uma empresa para venda de produtos agropecuários, e temos como objetivo principal cuidar da satisfação dos nossos clientes.
            </p>
          
          </div>
          <div className={styles.containerApresetation__image}>
          <Lottie 
            options={defaultOptions}
              height={400}
              width={400}
          />
          </div>
        </div>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}

export default Home
